### ISSUE TITLE
export xls impossible

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#108]
### What is the bug or the crash?

export xls de la synthèse par espèce impossible  : *

```
Traceback (most recent call last):
  File "", line 17, in 
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'openpyxl'
```

### Steps to reproduce the issue

via export sur bouton dans table attributaire

### Versions

3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by lpofredc** [comment]
Oui, j'ai eu ce même message, `ValueError: Cannot convert [8640] to Excel` correspond à la valeur du code espèce visionature.

Je n'ai pas touché à ce script. A creuser.

Pour le premier message, ça indique a priori que la librairie openpyxl n'est pas installée.
