### ISSUE TITLE
Ajouter la couche "zone d'étude" au projet si l'utilisateur sélectionne un fichier externe pour la définition de celle-ci

### ISSUE THREAD

**Issue by eguilley** [lpoaura/PluginQGis-LPOData#11]
Avec l'option `QgsProcessingParameterFeatureSource`, l'utilisateur peut sélectionner une zone d'étude qui n'est pas présente dans le projet (à l'aide des `...`). S'il choisit cette option, il est nécessaire d'ajouter la couche correspondante (fichier externe) au projet.

**Comment by lpojgc** [comment]
on en discute avant que tu creuses

**Comment by lpojgc** [comment]
tester le bon fonctionnement actuel
