### ISSUE TITLE
Problèmes d'installation

### ISSUE THREAD

**Issue by blaisegeo** [lpoaura/PluginQGis-LPOData#135]
Bonjour de la LPO Occitanie,

J'essaie d'installer ce plugin Qgis mais je bute sur les scripts sql.
J'ai bien créé les schémas dbadmin et src_lpodatas, puis j'ai tenté d'exécuter les scripts situés dans le sous-répertoire /config, mais je rencontre plusieurs erreurs :

mv_c_cor_vn_taxref.sql :
ERREUR: la relation « src_vn_json.species_json » n'existe pas

mv_source.sql :
Ok, vue matérialisée mv_source créée dans le schéma dbadmin

mv_statut.sql :
ERREUR: la relation « taxonomie.t_c_redlist » n'existe pas

mv_taxonomy_lpoaura.sql :
ERREUR: la relation « src_lpodatas.t_c_synthese_extended » n'existe pas

synthese.sql :
Ok, index créé

v_c_observations.sql :
ERREUR: la relation « taxonomie.t_c_redlist » n'existe pas

v_c_observations_light.sql :
ERREUR: la relation « src_lpodatas.t_c_synthese_extended » n'existe pas

Où puis-je trouver ces tables manquantes ?

Comme il est indiqué que la base de données de développement dispose des fonctionnalités de gn_2vnsynthese, j'ai essayé d'installer ce dernier, mais j'obtiens encore une erreur dès l'exécution du premier script sql 00_init_db.sql : ERREUR: le schéma « src_vn_json » n'existe pas.
D'où vient ce schéma src_vn_json qui est également nécessaire pour le plugin Qgis ?

**Comment by lpojgc** [comment]
Le schéma `src_vn_json`est le schéma utilisé pour impoerter les données depuis VN via le [client](https://github.com/dthonon/Client_API_VN).
Je pense qu'une partie des VM est obsolète, j'essaie de faire du ménage prochainement et pousser les modifs de codes faites.

**Comment by lpojgc** [comment]
j'ai mis à jour les codes des vues et vues matérialisées (https://github.com/lpoaura/PluginQGis-LPOData/pull/137).
à relire en détail, dans ce qu'il te manque :
- les schémas et tables provenant de client_api_vn
- t_c_redlist (mais dnas le code de la VM il est précisé que c'est à personnalisé), on avait utilisé cette table pour gérer des statuts LR pas officiels
