### ISSUE TITLE
Typo mineure dans le README.md

### ISSUE THREAD

**Issue by blaisegeo** [lpoaura/PluginQGis-LPOData#138]
### What is the bug or the crash?

Fichier README.md, ligne 19 : 

L'installation et l'utilisation sont documentatées [ici](https://github.com/lpoaura/PluginQGis-LPOData/wiki).

*documentées

### Steps to reproduce the issue

Read the doc

### Versions

3.3.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by lpojgc** [comment]
fait mais n'hésite pas à faire une PR directement
https://github.com/lpoaura/PluginQGis-LPOData/pull/141
