### ISSUE TITLE
Filtre : prise en compte des données d'absence

### ISSUE THREAD

**Issue by eguilley** [lpoaura/PluginQGis-LPOData#14]

**Comment by eguilley** [comment]
Critères (table `src_lpodatas.v_c_observations`) : 

- `nombre_total = 0`
- `code_estimation = EXACT_VALUE`

**Comment by eguilley** [comment]
Les données d'absence étant maintenant exclues par défaut, il s'agit d'ajouter une case à cocher proposant d'**inclure** les données d'absence.

**Comment by lpojgc** [comment]
données absences exclues des syntheèses mais inétgrées à l'extraction données brutes
