### ISSUE TITLE
Tableau Etat des connaissances : corriger la valeur de "Nombre d'espèces"

### ISSUE THREAD

**Issue by eguilley** [lpoaura/PluginQGis-LPOData#19]
1. Filtrer pour les espèces et sous-espèces : 
`COUNT(DISTINCT t.cd_ref) filter (WHERE t.id_rang in ('ES', 'SSES')) AS "Nb d'espèces"`

2. Remonter les sous-espèces au rang d'espèces : cf. #18 
Fonction (existante ou à écrire) qui retrouve le cd_ref de l'espèce à partir de celui de la sous-espèce 
`COUNT(DISTINCT FUNCTION(t.cd_ref)) filter (WHERE t.id_rang in ('ES', 'SSES')) AS "Nb d'espèces"`

**Comment by lpojgc** [comment]
choix fait de ne pas changer le fonctionnement actuel, les SSES ont des CDNOM valides, la fonction ne permettrait pas de régler le pb.
Par ailleurs demande marginale, il faudrait faire un `case when` pour récupérer le cd_sup des SSES mais trop lourd en performances
