### ISSUE TITLE
Filtre : sélection d'espèces particulières

### ISSUE THREAD

**Issue by eguilley** [lpoaura/PluginQGis-LPOData#21]
Difficilement envisageable pour l'instant, compte tenu de l'aspect non dynamique des fenêtres du plugin.

**Comment by eguilley** [comment]
Proposer un champ texte pour saisir le nom scientifique, et afficher un message d'erreur au lancement de l'algorithme si l'utilisateur fait une erreur de saisie ?

**Comment by lpofredc** [comment]
je propose d'aller plus loin en proposant un filtrage par cdnom OU nom scientifique (liste déroulante) avec plusieurs taxons séparés par des virgules?
