### ISSUE TITLE
Correction de code doublon dans les synthèses

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#29]
Le script summary_table_per_species.py générait des doublons dans le cas d'une expèce observée dans 2 sources différentes.
C'est corrigé dans le [ comit](https://github.com/lpoaura/PluginQGis-LPOData/commit/7eccc2d570ee321f04cd05427fc9f84823d9b8bc)
A voir si ça n'est pas présent dans d'autres requêtes

**Comment by eguilley** [comment]
:heavy_check_mark: Corrigé pour le Tableau de synthèse par intervalle de temps appliqué aux espèces observées
