### ISSUE TITLE
Problème de jointure

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#30]
J'ai modifié les jointures lignes 437 et 438 dans le [comit]( https://github.com/lpoaura/PluginQGis-LPOData/commit/7eccc2d570ee321f04cd05427fc9f84823d9b8bc)
Elles excluent les données qui ne proviennent pas de VN.
Voir si ça n'est pas le cas dasn d'autres requêtes

**Comment by eguilley** [comment]
:warning: Pour surpasser les doublons de cd_nom présents dans les vues matérialisées _taxonomie.vm_statut_lr_ et _taxonomie.vm_statut_protection_, j'ai de nouveau modifié les jointures : 
- `LEFT JOIN taxonomie.vm_statut_lr lr ON (obs.taxref_cdnom, obs.nom_sci) = (lr.cd_nom, lr.vn_nom_sci)`
- `LEFT JOIN taxonomie.vm_statut_protection p ON (obs.taxref_cdnom, obs.nom_sci) = (p.cd_nom, p.vn_nom_sci)`

Le recours au nom scientifique n'est pas très propre mais c'est fonctionnel le temps de trouver une meilleure solution...

**Comment by lpojgc** [comment]
réglé avec les reprises de structure de statuts
