### ISSUE TITLE
Nouvel algorithme : Stockage des paramètres en variables

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/PluginQGis-LPOData#34]
Il serait intéressant de stocker certains paramètres en variables plutôt que de les écrire en dur dans le code (notamment la base de données de connexion dans startup.py).

A voir si on ne peux pas ajouter un "algorithme" de configuration permettant de définir la base de données par défaut ainsi que la durée d'obsolescence des données stockées au démarrage (cf.  #33).

**Comment by lpofredc** [comment]
Et ajouter à cet algorithme la possibilité de rafraîchir les variables normalement chargées au démarrage, une fois la configuration mise à jour (cas ou on part d'une installation vierge ou lorsque l'on utilise différentes bases de données).

**Comment by eguilley** [comment]
Ajouter un script qui, suite au choix du nom de la connexion à la BDD, vérifie que la BDD en question est adaptée à l'utilisation du plugin :
- Récupérer la liste des noms de schémas de la BDD
- Vérifier que les schémas utilisés par le plugin sont bien compris dedans

**Comment by lpofredc** [comment]
On part du postulat qu'à partir du moment ou une connexion existe, l'utilisateur est garant que la bdd est bien adaptée.
