### ISSUE TITLE
Alimenter le README.md pour présenter le plugin et le processus d'installation

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/PluginQGis-LPOData#35]
tout est dans le titre.

**Comment by eguilley** [comment]
Pour la licence, regarder les autres plugins.

**Comment by lpojgc** [comment]
[fait](https://github.com/lpoaura/PluginQGis-LPOData/commit/76c7366aa0b69b5a5cedea18a0b22c7e146c5a53) à minima
