### ISSUE TITLE
Ajout filtre temporel

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#37]
Ajouter la possibilité, sur les filtres temporels d'avoir "cette année" => du 1er janvier à la date du jour.
Permet d'extraire rapidement les données d'une étude réalisée sur l'année

**Comment by afourneyron** [comment]
fait via le commit : https://github.com/lpoaura/PluginQGis-LPOData/commit/2249a49480f2a7963ae3ec7ba1ea69226befc7be 
sur l'ensemble des fonctionnalités du plugin qui utilise les dates (extraction data, état des connaissances, tableau de synthèse par espèces, carte de synthèse)
