### ISSUE TITLE
Export : problème titre couche

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#38]
lors de l'export evrs un fichier, la couche se charge dans qgis avec un nom à revoir 
![image](https://user-images.githubusercontent.com/51160496/101914392-8bcc8f80-3bc4-11eb-9881-5986e22b39e6.png)
merci !

**Comment by eguilley** [comment]
En théorie on ne peut rien y faire à travers le plugin... Par contre, ça peut être amélioré en changeant un paramètre de QGis, c'est expliqué dans le tuto
