### ISSUE TITLE
Compatibilité QGIS 3.14+

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/PluginQGis-LPOData#39]
Voir sur ce dépot [ygversil/qgis-plugin-csv-tools](https://github.com/ygversil/qgis-plugin-csv-tools) qui utilisait aussi le module `postgis`, notamment ce commit https://github.com/ygversil/qgis-plugin-csv-tools/commit/13642bc96ab6f3d1bed81db9b33b310f1eb7d305#diff-09d0cbaf891d623ac245ccf84485a687b554217349ca55557c60b33234b969ae

**Comment by eguilley** [comment]
Solution choisie : cf. https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/python/plugins/processing/algs/qgis/PostGISExecuteAndLoadSQL.py
