### ISSUE TITLE
Mutualisation la liste "queries"

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/PluginQgis-LPOData#4]
La liste `queries` est systématiqmenet utilisée dans chaque scripts.

```python
            queries = [
                "DROP TABLE if exists {}".format(table_name),
                "CREATE TABLE {} AS ({})".format(table_name, query),
                "ALTER TABLE {} add primary key (id)".format(table_name)
            ]
```

En faire une fonction partagée à appeler dans chacun des scripts.

**Comment by eguilley** [comment]
Fonction `construct_queries_list(table_name, main_query)` créée dans common_functions.py
