### ISSUE TITLE
Gestion de l'aide

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#43]
une idée :  https://static.geotribu.fr/articles/2021/2021-03-09_pyqgis_astuce_aide_plugin/

**Comment by lpofredc** [comment]
Liens vers l'aide en ligne maintenant dans les menus de QGIS depuis la version 3.0.0 :

- Aide > Extensions > Plugin LPO
- Extensions > Plugin LPO > Help
