### ISSUE TITLE
[Cartes espèces] Ajouter l'url des données source

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/PluginQGis-LPOData#66]
Ajouter aux tables de données la référence biblio de la donnée.
Exemple pour les données Visionature (contenu du champ `gn_synthese.synthese.reference_biblio`):

`https://www.faune-ain.org/index.php?m_id=54&id=<id visionature>`

ou avec l'id universel visionature
`https://www.faune-ain.org/index.php?m_id=54&uid=<id universel visionature>`

pour dbchiro ce serait:
`https://monsite.dbchiro.org/sighting/<id sighting>/detail`

**Comment by lpojgc** [comment]
euh... c'est déjà le cas, le chhamp ref_biblio est peuplé pour les données vn depuis la synthèse.

par contre ça n'est pas le cas pour les données dbchiro

**Comment by lpofredc** [comment]
Pas dans les résultats de la nouvelle fonctionnalité de la "carte par espèces"

![image](https://user-images.githubusercontent.com/22891423/191217325-ed86e921-a054-454e-96b3-d3c93a77ab13.png)

**Comment by lpojgc** [comment]
ah ok, je n'y étais pas du tout, j'étais sur l'extraction de données brutes.

pour cette fonctionnalité il reste pas mal de choses à faire... je ne la considère pas encore comme étant opérationnelle...

**Comment by lpojgc** [comment]
ajouter le champ biblio de la synthèse

**Comment by lpojgc** [comment]
géré côté qgis, reste à le peupler en sytnhèse
