### ISSUE TITLE
[cartes espèces] visualisation des données d'absence

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#67]
representer les données d'absence avec le champ is_present  plu^tot que par les codes atals car toutes les données d'absence n'en ont pas forcément...

**Comment by afourneyron** [comment]
changement fait sur https://github.com/lpoaura/PluginQGis-LPOData/commit/7b27e16a2457796723cfb88b2766e193bc5dd6ad
