### ISSUE TITLE
export de couche de données

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#70]
la restitution des données non ponctuelles n'est pas gérée visiblement, la vue les gère mais pas la restitution côté QGIS

**Comment by lpojgc** [comment]
tester le fonctionnement actuel en supprimant le `WHERE st_geometrytype(s.the_geom_local) = 'ST_Point'::text;` de `v_c_observations`

**Comment by afourneyron** [comment]
Fonction opérationnelle.
Cependant, attention, nous n'avons pas de géométrie de ligne ou de polygone valide pour le moment, ce qui créer un bug lors de l'extraction.
Amélioration plus propre à prévoir avec message d'alerte.
