### ISSUE TITLE
optimisation requete random_page_cost

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#71]
ajouter paramètre ci-dessous 
 set random_page_cost to 4;
dans la requete [ici](https://github.com/lpoaura/PluginQGis-LPOData/blob/0a8d0151bc2dce09a179a5ad55927e7b3251ea21/summary_map.py#L420)

**Comment by lpojgc** [comment]
je viens de pousser les modifs que j'avais faites, le paramètre est [commenté](https://github.com/lpoaura/PluginQGis-LPOData/blob/ac5ed75f4a99a161a33bb0a6999f45bfb1d2bf69/summary_map.py#L420)
quand on l'exécute avant un `select`ça fonctionne mais écrit comme ça dans la requête, ça le rentre dans le `select`.

**Comment by lpojgc** [comment]
solution non trouvée, recherche en cours

**Comment by lpofredc** [comment]
Question posée sur stackoverflow:
https://stackoverflow.com/questions/76710684/changing-postgresql-database-parameters-for-a-specific-query-with-pyqgis

**Comment by lpofredc** [comment]
Je ferme, faut de réponse et vraiment dépendant de notre config bdd.
