### ISSUE TITLE
[carte espèce] reprise sql

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/PluginQGis-LPOData#76]
dans la requete species_map.py, ajouter
   ````sql s.id_nomenclature_valid_status = ANY (ARRAY[ref_nomenclatures.get_id_nomenclature('STATUT_VALID'::character varying, 
    s.id_nomenclature_observation_status = ref_nomenclatures.get_id_nomenclature('STATUT_OBS'::character varying, 'Pr'::character varying) AS is_present,
````
pour pouvoir gérer https://github.com/lpoaura/PluginQGis-LPOData/issues/67 et modifier la clause where de la requete remplacer is_valid
à faire avant les tickets https://github.com/lpoaura/PluginQGis-LPOData/issues/60 et https://github.com/lpoaura/PluginQGis-LPOData/issues/67

**Comment by afourneyron** [comment]
Ligne ajoutée dans la requête voir species_map.py ligne 232
modif https://github.com/lpoaura/PluginQGis-LPOData/commit/7b27e16a2457796723cfb88b2766e193bc5dd6ad
